#!/usr/bin/env python3
"""
Run EvoClaw E2E trials across multiple repositories in parallel.

Reads a trial_config.yaml, discovers repos in data_root,
and launches run_e2e.py for each repo with controlled parallelism.

Usage:
    python scripts/run_all.py --config trial_config.yaml
    python scripts/run_all.py --config trial_config.yaml --max-parallel 2
    python scripts/run_all.py --config trial_config.yaml --repos navidrome ripgrep
"""

import argparse
import os
import re
import subprocess
import sys
import threading
import time
from pathlib import Path

import yaml


def discover_repos(data_root: Path, repo_filters: list[str] | None = None) -> list[Path]:
    """Find all repo directories in data_root that contain metadata.json."""
    repos = []
    for d in sorted(data_root.iterdir()):
        if not d.is_dir():
            continue
        if not (d / "metadata.json").exists():
            continue
        if repo_filters:
            # Substring match: "navidrome" matches "navidrome_navidrome_v0.57.0_v0.58.0"
            if not any(f in d.name for f in repo_filters):
                continue
        repos.append(d)
    return repos


def get_image_name(repo_name: str) -> str:
    """Derive Docker image name from repo directory name.

    Docker image names must be lowercase.
    """
    return f"{repo_name.lower()}/base:latest"


def generate_collect_config(
    config_dir: Path,
    trial_name: str,
    data_root: Path,
    repos: list[Path],
) -> Path:
    """Generate a collect_results config file for monitoring."""
    config_dir.mkdir(parents=True, exist_ok=True)
    config_file = config_dir / f"{trial_name}_collect.py"

    mapping_lines = []
    for repo in repos:
        mapping_lines.append(f'    "{repo.name}": {{"path": "{repo.name}"}},')

    content = f'''# Auto-generated by run_all.py for trial: {trial_name}
# Usage: python -m harness.e2e.collect_results --multi-repo --config {config_file}

DATA_ROOT = "{data_root}"

WORKSPACE_MAPPING = {{
{chr(10).join(mapping_lines)}
}}

E2E_TRIAL_NAMES = ["{trial_name}"]
'''
    config_file.write_text(content)
    return config_file


def run_repo(
    repo: Path,
    agent: str,
    model: str,
    timeout: int,
    trial_name: str,
    reasoning_effort: str | None,
    api_router: bool,
    force: bool,
    semaphore: threading.Semaphore,
    results: dict,
):
    """Run a single repo trial. Called in a thread."""
    repo_name = repo.name
    image = get_image_name(repo_name)
    srs_root = repo / "srs"
    workspace_root = repo

    # Force mode: remove existing trial directory and start fresh
    trial_dir = workspace_root / "e2e_trial" / trial_name
    if force and trial_dir.exists():
        import shutil
        print(f"\033[0;33m[FORCE]\033[0m  {repo_name}  (removing existing trial dir)")
        try:
            shutil.rmtree(trial_dir)
        except PermissionError:
            # Docker-created files may be root-owned; use a container to remove
            subprocess.run(
                ["docker", "run", "--rm", "-v", f"{trial_dir}:/data", "alpine", "rm", "-rf", "/data"],
                capture_output=True, timeout=30,
            )
            if trial_dir.exists():
                shutil.rmtree(trial_dir)

    # Check if trial already exists for this repo → skip if done, auto-resume if incomplete
    metadata_path = trial_dir / "trial_metadata.json"
    can_resume = trial_dir.exists() and metadata_path.exists()
    if can_resume:
        # Check if trial already completed (has summary with all milestones done)
        summary_path = trial_dir / "evaluation" / "summary.json"
        if summary_path.exists():
            try:
                import json as _json
                with open(summary_path) as _f:
                    _summary = _json.load(_f)
                _rs = _summary.get("resume_state", {})
                _completed = set(_rs.get("completed_milestones", []))
                _total = _summary.get("total_milestones", 0)
                if _total > 0 and len(_completed) >= _total:
                    elapsed_str = "0:00:00"
                    print(f"\033[0;34m[SKIP]\033[0m   {repo_name}  (already completed)")
                    results[repo_name] = ("success", 0)
                    return
            except Exception:
                pass

        cmd = [
            sys.executable, "-m", "harness.e2e.run_e2e",
            "--resume-trial", str(trial_dir),
        ]
    else:
        # Clean up incomplete trial directory (no metadata = never initialized)
        if trial_dir.exists():
            import shutil
            print(f"\033[0;33m[CLEAN]\033[0m  {repo_name}  (removing incomplete trial dir)")
            shutil.rmtree(trial_dir)

        cmd = [
            sys.executable, "-m", "harness.e2e.run_e2e",
            "--repo-name", repo_name,
            "--image", image,
            "--srs-root", str(srs_root),
            "--workspace-root", str(workspace_root),
            "--agent", agent,
            "--model", model,
            "--timeout", str(timeout),
            "--trial-name", trial_name,
        ]
        if reasoning_effort:
            cmd.extend(["--reasoning-effort", reasoning_effort])
        if api_router:
            cmd.append("--api-router")
        if force:
            cmd.append("--force")

    with semaphore:
        print(f"\033[0;32m[START]\033[0m  {repo_name}")
        start_time = time.time()

        try:
            proc = subprocess.run(
                cmd,
                cwd=str(Path(__file__).resolve().parent.parent),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            elapsed = time.time() - start_time
            elapsed_str = time.strftime("%H:%M:%S", time.gmtime(elapsed))

            if proc.returncode == 0:
                print(f"\033[0;32m[DONE]\033[0m   {repo_name}  ({elapsed_str})")
                results[repo_name] = ("success", elapsed)
            else:
                print(f"\033[0;31m[FAIL]\033[0m   {repo_name}  ({elapsed_str})  exit={proc.returncode}")
                results[repo_name] = ("failed", elapsed)

                # Write log for debugging
                log_file = Path(__file__).resolve().parent.parent / ".evoclaw" / f"{repo_name}.log"
                log_file.parent.mkdir(parents=True, exist_ok=True)
                log_file.write_text(proc.stdout or "")

        except Exception as e:
            elapsed = time.time() - start_time
            print(f"\033[0;31m[ERROR]\033[0m  {repo_name}  {e}")
            results[repo_name] = ("error", elapsed)


def main():
    parser = argparse.ArgumentParser(description="Run EvoClaw trials across all repos")
    parser.add_argument("--config", type=Path, required=True, help="Path to trial_config.yaml")
    parser.add_argument("--max-parallel", type=int, default=None, help="Override max parallel repos")
    parser.add_argument("--repos", nargs="+", default=None, help="Override repo filters")
    parser.add_argument("--force", action="store_true",
                        help="Remove existing trial directories and containers before starting fresh")
    args = parser.parse_args()

    # Load config
    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    data_root = Path(cfg["data_root"]).expanduser().resolve()
    trial_name = cfg["trial_name"]
    # Ensure trial_name has a numeric suffix so run_e2e uses it as-is
    # (without auto-incrementing), and collect_results can find it exactly.
    if not re.match(r".*_\d{3}$", trial_name):
        trial_name = f"{trial_name}_001"
    agent = cfg.get("agent", "claude-code")
    model = cfg.get("model", "claude-sonnet-4-5-20250929")
    timeout = cfg.get("timeout", 18000)
    reasoning_effort = cfg.get("reasoning_effort", None)
    api_router = cfg.get("api_router", cfg.get("drop_params", False))
    max_parallel = args.max_parallel if args.max_parallel is not None else cfg.get("max_parallel", None)
    repo_filters = args.repos or cfg.get("repos", None)

    # Validate
    if not data_root.exists():
        print(f"Error: data_root not found: {data_root}")
        sys.exit(1)

    # Check API key
    if not os.environ.get("UNIFIED_API_KEY"):
        print("Warning: UNIFIED_API_KEY not set. Agents may fail to authenticate.")

    # Discover repos
    repos = discover_repos(data_root, repo_filters)
    if not repos:
        print(f"Error: no repos found in {data_root}")
        sys.exit(1)

    # Set parallelism
    if max_parallel is None:
        max_parallel = len(repos)
    semaphore = threading.Semaphore(max_parallel)

    # Print plan
    print(f"{'='*60}")
    print(f"  EvoClaw Run All")
    print(f"{'='*60}")
    print(f"  Data root:    {data_root}")
    print(f"  Trial name:   {trial_name}")
    print(f"  Agent:        {agent}")
    print(f"  Model:        {model}")
    print(f"  Timeout:      {timeout}s")
    print(f"  Repos:        {len(repos)}")
    print(f"  Parallelism:  {max_parallel}")
    print(f"{'='*60}")
    for repo in repos:
        print(f"    - {repo.name}")
    print()

    # Generate collect config for monitoring
    project_root = Path(__file__).resolve().parent.parent
    config_file = generate_collect_config(
        config_dir=project_root / ".evoclaw",
        trial_name=trial_name,
        data_root=data_root,
        repos=repos,
    )
    print(f"Monitor progress:  ./scripts/monitor.sh {trial_name}")
    print(f"Collect config:    {config_file}")
    print()

    # Launch all repos
    results: dict[str, tuple[str, float]] = {}
    threads = []
    start_time = time.time()

    for repo in repos:
        t = threading.Thread(
            target=run_repo,
            args=(repo, agent, model, timeout, trial_name, reasoning_effort, api_router, args.force, semaphore, results),
            daemon=True,
        )
        threads.append(t)
        t.start()

    # Wait for all to complete
    for t in threads:
        t.join()

    total_elapsed = time.time() - start_time
    total_str = time.strftime("%H:%M:%S", time.gmtime(total_elapsed))

    # Print summary
    print()
    print(f"{'='*60}")
    print(f"  Summary  (total: {total_str})")
    print(f"{'='*60}")

    success = sum(1 for s, _ in results.values() if s == "success")
    failed = sum(1 for s, _ in results.values() if s != "success")

    for repo_name, (status, elapsed) in sorted(results.items()):
        elapsed_str = time.strftime("%H:%M:%S", time.gmtime(elapsed))
        icon = "\033[0;32m✓\033[0m" if status == "success" else "\033[0;31m✗\033[0m"
        print(f"  {icon}  {repo_name:<55} {elapsed_str}")

    print()
    print(f"  {success} succeeded, {failed} failed")
    print(f"  Results: ./scripts/monitor.sh {trial_name}")
    print()


if __name__ == "__main__":
    main()
